version: 0.2

env:
  variables:
    ACCOUNT_ID: 235494811179
    REGION: us-east-1
    FRONTEND_REPO: kaushal-frontend-ecr
    BACKEND_REPO: kaushal-backend-ecr
    FRONTEND_DIR: react-frontend
    BACKEND_DIR: springboot-backend

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
      - echo Installing jq...
      - yum install -y jq

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - export IMAGE_TAG=v1.${CODEBUILD_BUILD_NUMBER}
      - echo Using image tag: $IMAGE_TAG
      - echo Installing frontend dependencies...
      - cd $FRONTEND_DIR && npm install && cd -
      - echo Building backend JAR...
      - cd $BACKEND_DIR && ./mvnw package -DskipTests && cd -

  build:
    commands:
      - echo Building Docker images...
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG $FRONTEND_DIR
      - docker tag $FRONTEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - docker build -t $BACKEND_REPO:$IMAGE_TAG $BACKEND_DIR
      - docker tag $BACKEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG
      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG|g" react-frontend/frontend-deployment.yaml > k8s-out/frontend-deployment.yaml
      - cp react-frontend/frontend-service.yaml k8s-out/frontend-service.yaml
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG|g" springboot-backend/backend-deployment.yaml > k8s-out/backend-deployment.yaml
      - cp springboot-backend/backend-service.yaml k8s-out/backend-service.yaml
      - echo Kubernetes YAMLs generated:
      - ls -la k8s-out

artifacts:
  base-directory: k8s-out
  discard-paths: yes
  files:
    - '**/*.yaml'

cache:
  paths:
    - 'react-frontend/node_modules/**/*'
    - '/root/.m2/**/*'
