version: 0.2

env:
  variables:
    ACCOUNT_ID: 235494811179
    REGION: us-east-1
    FRONTEND_REPO: kaushal-frontend-ecr
    BACKEND_REPO: kaushal-backend-ecr
    FRONTEND_DIR: react-frontend
    BACKEND_DIR: springboot-backend

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - echo Build started on `date`
      - export IMAGE_TAG="$CODEBUILD_BUILD_NUMBER"
      - echo Using image tag: $IMAGE_TAG

  build:
    commands:
      - echo Building backend Docker image...
      - cd $BACKEND_DIR
      - docker build -t $BACKEND_REPO:$IMAGE_TAG .
      - docker tag $BACKEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG
      - cd ../$FRONTEND_DIR
      - echo Building frontend Docker image...
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG .
      - docker tag $FRONTEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG

      - echo Updating and applying backend Kubernetes manifests...
      - cd ../$BACKEND_DIR
      - sed -i "s|PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG|" backend-deployment.yaml
      - kubectl apply -f backend-deployment.yaml
      - kubectl apply -f backend-service.yaml

      - echo Updating and applying frontend Kubernetes manifests...
      - cd ../$FRONTEND_DIR
      - sed -i "s|PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG|" frontend-deployment.yaml
      - kubectl apply -f frontend-deployment.yaml
      - kubectl apply -f frontend-service.yaml

      - echo Deployment completed on `date`
