version: 0.2

phases:
  install:
    commands:
      - echo "Assuming kubectl is already installed"

  pre_build:
    commands:
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region us-east-1 --name kaushal-cluster

  build:
    commands:
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f k8s-out/

artifacts:
  base-directory: k8s-out
  discard-paths: yes
  files:
    - '**/*.yaml'
