version: 0.2

env:
  variables:
    ACCOUNT_ID: 235494811179
    REGION: us-east-1
    FRONTEND_REPO: kaushal-frontend-ecr
    BACKEND_REPO: kaushal-backend-ecr
    FRONTEND_DIR: react-frontend
    BACKEND_DIR: springboot-backend
    EKS_CLUSTER_NAME: kaushal-cluster   # 🔁 Replace this with your EKS cluster name

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing utilities...
      - yum install -y jq unzip curl

      - echo Installing kubectl...
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.1/2024-05-10/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/

      - echo Verifying kubectl version...
      - kubectl version --client

  pre_build:
    commands:
      - echo Setting image tag from build number...
      - export IMAGE_TAG=build-${CODEBUILD_BUILD_NUMBER}
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

      - echo Installing frontend dependencies...
      - cd $FRONTEND_DIR && npm install && cd -

  build:
    commands:
      - echo Building Docker images...
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG $FRONTEND_DIR
      - docker tag $FRONTEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - docker build -t $BACKEND_REPO:$IMAGE_TAG $BACKEND_DIR
      - docker tag $BACKEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Skipping Docker push to ECR...
      # - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      # - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out

      # FRONTEND
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG|g" $FRONTEND_DIR/frontend-deployment.yaml > k8s-out/frontend-deployment.yaml
      - cp $FRONTEND_DIR/frontend-service.yaml k8s-out/frontend-service.yaml

      # BACKEND
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG|g" $BACKEND_DIR/backend-deployment.yaml > k8s-out/backend-deployment.yaml
      - cp $BACKEND_DIR/backend-service.yaml k8s-out/backend-service.yaml

      - echo Updating kubeconfig for EKS cluster...
      - aws eks update-kubeconfig --region $REGION --name $EKS_CLUSTER_NAME

      - echo Checking EKS connectivity...
      - kubectl get nodes

      - echo Deploying manifests to EKS...
      - kubectl apply -f k8s-out/

artifacts:
  base-directory: k8s-out
  discard-paths: yes
  files:
    - '**/*.yaml'

cache:
  paths:
    - 'react-frontend/node_modules/**/*'
