version: 0.2

env:
  variables:
    ACCOUNT_ID: 235494811179
    REGION: us-east-1
    FRONTEND_REPO: kaushal-frontend-ecr
    BACKEND_REPO: kaushal-backend-ecr
    FRONTEND_DIR: react-frontend
    BACKEND_DIR: springboot-backend

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - export IMAGE_TAG=build-${CODEBUILD_BUILD_NUMBER}
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo Building frontend Docker image...
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG $FRONTEND_DIR
      - docker tag $FRONTEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG

      - echo Building backend Docker image...
      - cd $BACKEND_DIR && ./mvnw clean package -DskipTests && cd -
      - docker build -t $BACKEND_REPO:$IMAGE_TAG $BACKEND_DIR
      - docker tag $BACKEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG|g" $FRONTEND_DIR/frontend-deployment.yaml > k8s-out/frontend-deployment.yaml
      - cp $FRONTEND_DIR/frontend-service.yaml k8s-out/frontend-service.yaml

      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG|g" $BACKEND_DIR/backend-deployment.yaml > k8s-out/backend-deployment.yaml
      - cp $BACKEND_DIR/backend-service.yaml k8s-out/backend-service.yaml

      - echo Kubernetes manifests prepared:
      - ls -la k8s-out

artifacts:
  base-directory: k8s-out
  discard-paths: yes
  files:
    - '**/*.yaml'
