version: 0.2

phases:
  install:
    commands:
      - echo "Installing phase..."
  pre_build:
    commands:
      - echo "Pre-build phase..."
  build:
    commands:
      - echo "Hello, World! ✅ Build is successful."
  post_build:
    commands:
      - echo "Post-build phase completed."

artifacts:
  files:
    - '**/*'
