version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo "Hello World from CodeBuild!"

  post_build:
    commands:
      - echo Build complete.
