version: 0.2

phases:
  install:
    commands:
      - echo "Assuming kubectl is already installed"

  pre_build:
    commands:
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region us-east-1 --name kaushal-cluster

  build:
    commands:
      - echo "Applying frontend manifests..."
      - kubectl apply -f react-frontend/frontend-deployment.yaml
      - kubectl apply -f react-frontend/frontend-service.yaml

      - echo "Applying backend manifests..."
      - kubectl apply -f springboot-backend/backend-deployment.yaml
      - kubectl apply -f springboot-backend/backend-service.yaml
