version: 0.2

env:
  variables:
    REGION: "us-east-1"
    EKS_CLUSTER_NAME: "kaushal-cluster"
    FRONTEND_DIR: "react-frontend"
    BACKEND_DIR: "springboot-backend"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Assuming kubectl is preinstalled"
      - echo "Skipping Docker login and build"

  pre_build:
    commands:
      - echo "Updating kubeconfig for EKS cluster..."
      - aws eks update-kubeconfig --region $REGION --name $EKS_CLUSTER_NAME

  build:
    commands:
      - echo "Skipping Docker build and push"
      - echo "Proceeding to deployment only..."

  post_build:
    commands:
      - echo "Verifying access to EKS..."
      - kubectl get nodes || echo "kubectl failed, continuing anyway..."

      - echo "Applying frontend Kubernetes manifests..."
      - kubectl apply -f $FRONTEND_DIR/frontend-deployment.yaml --validate=false
      - kubectl apply -f $FRONTEND_DIR/frontend-service.yaml --validate=false

      - echo "Applying backend Kubernetes manifests..."
      - kubectl apply -f $BACKEND_DIR/backend-deployment.yaml --validate=false
      - kubectl apply -f $BACKEND_DIR/backend-service.yaml --validate=false

artifacts:
  files:
    - '**/*.yaml'
