apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: frontend
          image: 235494811179.dkr.ecr.us-east-1.amazonaws.com/kaushal-frontend-ecr
          ports:
            - containerPort: 80
